interface Participant {
    name: string;
    phone: string;
    type: 'volunteer' | 'guest';
    role?: string;
    points?: number;
}

interface GroupSubmissionData {
    leaderName: string;
    activityName: string;
    committeeName: string;
    date: string;
    participants: Participant[];
}

export const generateGroupSubmissionCSV = (data: GroupSubmissionData): Blob => {
    // Helper to escape CSV values
    const escape = (val: string | number | undefined | null) => {
        if (val === undefined || val === null) return '';
        const str = String(val);
        if (str.includes(',') || str.includes('"') || str.includes('\n')) {
            return `"${str.replace(/"/g, '""')}"`;
        }
        return str;
    };

    // Calculate totals
    const totalParticipants = data.participants.length;
    const totalPoints = data.participants.reduce((sum, p) => sum + (p.points || 0), 0);
    const volunteers = data.participants.filter(p => p.type === 'volunteer').length;
    const guests = data.participants.filter(p => p.type === 'guest').length;

    const rows = [
        // Header
        ['RTC MOHANDSEEN - GROUP ACTIVITY REPORT'],
        ['─'.repeat(80)],
        [],

        // Submission Information
        ['SUBMISSION DETAILS', ''],
        ['Activity Name | اسم النشاط:', data.activityName],
        ['Committee | اللجنة:', data.committeeName],
        ['Submitted By | تم التسجيل بواسطة:', data.leaderName],
        ['Date | التاريخ:', data.date],
        [],

        // Summary Statistics
        ['SUMMARY | الملخص', ''],
        ['Total Participants | إجمالي المشاركين:', totalParticipants.toString()],
        ['Volunteers | متطوعين:', volunteers.toString()],
        ['Guests | ضيوف:', guests.toString()],
        ['Total Points | إجمالي النقاط:', totalPoints.toString()],
        [],
        ['─'.repeat(80)],
        [],

        // Participants Table Header
        ['#', 'Participant Name | اسم المشارك', 'Phone | رقم الهاتف', 'Type | النوع', 'Role | الدور', 'Points | النقاط']
    ];

    // Add participants with numbering
    data.participants.forEach((p, index) => {
        // Format phone number to preserve +20 in Excel using single quote
        // Excel treats anything starting with ' as text (not displayed but forces text mode)
        const formattedPhone = p.phone ? `'${p.phone}` : '-';

        rows.push([
            (index + 1).toString(),
            p.name,
            formattedPhone,
            p.type === 'volunteer' ? 'Volunteer | متطوع' : 'Guest | ضيف',
            p.role || '-',
            p.points?.toString() || '-'
        ]);
    });

    // Footer
    rows.push(
        [],
        ['─'.repeat(80)],
        ['TOTALS | الإجمالي', '', '', '', 'Total Points:', totalPoints.toString()],
        [],
        ['Generated by RTC Mohandseen Activity Tracking System'],
        [`Report Date: ${new Date().toLocaleString('en-US', { dateStyle: 'full', timeStyle: 'short' })}`]
    );

    const csvContent = rows.map(row => row.map(escape).join(',')).join('\n');

    // Add BOM for Excel compatibility with UTF-8 (important for Arabic text)
    return new Blob(['\ufeff' + csvContent], { type: 'text/csv;charset=utf-8;' });
};
