CREATE TABLE IF NOT EXISTS public.users_followup (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    phone_1 TEXT NOT NULL,
    phone_2 TEXT,
    branch TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.users_followup ENABLE ROW LEVEL SECURITY;

-- Create policies to allow authenticated users to manage the table
CREATE POLICY "Allow read access for all authenticated users" 
ON public.users_followup FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Allow insert access for all authenticated users" 
ON public.users_followup FOR INSERT 
TO authenticated 
WITH CHECK (true);

CREATE POLICY "Allow update access for all authenticated users" 
ON public.users_followup FOR UPDATE 
TO authenticated 
USING (true);

CREATE POLICY "Allow delete access for all authenticated users" 
ON public.users_followup FOR DELETE 
TO authenticated 
USING (true);
